services:
  - type: web
    name: automax
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn automex.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: automex.settings
      - key: PYTHON_VERSION
        value: 3.10
